### ISSUE TITLE
ロール系コマンドが正常に動作しない

### ISSUE THREAD

**Issue by gimKondo** [cahlchang/CoCNonKP#18]
## 再現手順

1. `/cc 1D6` 、 `/cc 2D6` 等を打つ
2. `/cc 1D1` 、 `/cc 2D2` などの結果が返ってくる
    - `/cc mDn` に対して、 `/cc mDm` の結果が返っている

**Comment by Curosiz** [comment]
dice_count = int(match_roll.group(1))
            dice_type = int(match_roll.group(1))
で同一の数字が入ってしまっているのだと思う

**Comment by gimKondo** [comment]
resolved by #20
