### ISSUE TITLE
Please add command reference to README

### ISSUE THREAD

**Issue by nagashima-w** [cahlchang/CoCNonKP#8]
機能追加によってサブコマンドがどんどん充実してきているので、READMEのデプロイ手順の下にコマンドリファレンスがあると嬉しいです

**Comment by cahlchang** [comment]
https://github.com/cahlchang/CoCNonKP/wiki

ドキュメント作りました。
このドキュメントで使いやすくなるでしょうか？

**Comment by nagashima-w** [comment]
LGTM！感謝！
